### ISSUE TITLE
randomly crashing due to "Cannot read properties of null at Component.updateFromGamepad"

### ISSUE THREAD

**Issue by DerKorb** [coconut-xr/natuerlich#8]
This keeps happening to me after some while. My assumption would be the controller might disappear while quest switches from controllers to hand tracking or so.

Uncaught TypeError: Cannot read properties of null (reading 'buttons')
    at Component.updateFromGamepad

**Comment by DerKorb** [comment]
Tried it with https://coconut-xr.github.io/apfel-kruemel/examples/#/buttons, same behaviour. As soon as I lay my controller on the desk it takes less than a second to crash

**Comment by DerKorb** [comment]
So apparently this is happening because the quest is switching to hands and a motioncontroller is created from an xInputSource that does not have a gamepad (the hand)

**Comment by wrangelvid** [comment]
+1 I have the same issue.

**Comment by bbohlender** [comment]
@DerKorb @wrangelvid can you share the code you're using. It might be that you are rendering your hands as Controllers

**Comment by wrangelvid** [comment]
> @DerKorb @wrangelvid can you share the code you're using. It might be that you are rendering your hands as Controllers

I isolated the bug to this line:
`<Controllers type="pointer" />`

In contrary the hands work with no issues:
<Hands type="grab" />

I can put a minimum reproducible example together after I get back to the headset in an hour or so.

**Comment by bbohlender** [comment]
@wrangelvid are you requesting the `hand-tracking` feature when entering the sesseion?
Yes a minimum example would be nice

**Comment by wrangelvid** [comment]
@bbohlender yes, I request as an optional feature `hand-tracking`.

Sounds good, I will create an example soon :)

**Comment by DerKorb** [comment]
As I stated earlier, the apfel-kruemmel examples are more or less a minimum example. I also use hand-tracking and <Hands type="pointer"> as well as <Controllers type="pointer">.
I "fixed" the crashes for the time beeing using this vite plugin to modify the code in @webxr/input-sources:

```ts
export function monkeyPatchPlugin() {
  return {
    name: 'monkey-patch-plugin',
    transform(code, id) {
      if (code.includes('updateFromGamepad(gamepad)')) {
        const updatedCode = code
          .replace(
            /updateFromGamepad\(gamepad\)\s*{/,
            `updateFromGamepad(gamepad) {
            if (!gamepad) return;`
          )
          .replace(
            /}\s*}\s*$/,
            `}
          }
        }`
          )
        return updatedCode
      }
      return null
    },
  }
}
```

**Comment by bbohlender** [comment]
Should be fixed in v0.0.51

**Comment by DerKorb** [comment]
I think it is not fixed yet, still have crashes with 51, had to reenable my monkeypatch. I think this might be an issue upstream.

**Comment by bbohlender** [comment]
So there was a behavior change (right when the controllers are switched of the gamepad becomes null, which previously didnt) but I would call it an issue upstream, since it is expectable that a switched off controller does not have a accessible gamepad. I'll check again to see if other problems occured
